# Generated by Django 5.0.6 on 2024-05-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.URLField(default='https://picsum.photos/97/77'),
        ),
    ]
